version: '3.8'
services:
  db:
    image: timescale/timescaledb:latest-pg15
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d 
    environment:
      POSTGRES_USER:   ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB:     ${DB_NAME}
    ports:
      - "5432:5432"

  # Optional: a lightweight admin UI for local testing
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  db-data:
